# Generated by Django 3.1.3 on 2020-11-30 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_culture_datescults_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datescults',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datescults',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.myfuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datescults',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='harvest_time',
            field=models.DateField(),
        ),
    ]
