# Generated by Django 3.1.3 on 2020-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201130_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='datescults',
            name='coordinates',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='harvest_time',
            field=models.IntegerField(),
        ),
    ]
