# Generated by Django 3.1.3 on 2020-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201130_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='normal_earth_weat',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='normal_temperature',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='culture',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
