# Generated by Django 3.1.3 on 2020-12-01 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201130_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datescults',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='field',
            name='cultures',
        ),
        migrations.AddField(
            model_name='datescults',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='real_state',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
